### ISSUE TITLE
FYI: Module tested and seems to be working

### ISSUE THREAD

**Issue by wx4cb** [OlivierC-FR/ESP32-INAV-Radar#6]
@OlivierC-FR 

just an FYI, you can add these to your working list with stock firmware. Havent done a flight test as i'm the only one that has inav at the minute, but on the bench they seem to work fine

https://www.ebay.com/itm/184468688127?var=692173575079

**Comment by OlivierC-FR** [comment]
Ok thanks, I'll add a new target, even if it's the same pinouts as the Lilygos 1.0.
Just to be sure, you're confirming you have 2 seeing each other on the ground, and at least one sees the flight controller it's attached to ? With INAV version etc ?

**Comment by wx4cb** [comment]
Correct, i have 3 total boards, 1 in a plane and sees inav v4rc1 fine and the other two on the bench and they all see each other..

Three total nodes a, b, c

now as far as the osd side. as I say, i havent tested that, but i did just find out about it supposedly working with mwptools so i'll see how that goes and see if i can find it as a GCS
